Ask the user for consent before configuring.
Move the notification banners into the wrapper script, and interactively
ask the user for final consent before reconfiguring their system. The
interactive prompt can be skipped by passing the `-y` arg to the wrapper
script.

Signed-off-by: Alex Stewart <alex.stewart@ni.com>

diff --git a/src/nilrt-snac b/src/nilrt-snac
--- a/src/nilrt-snac
+++ b/src/nilrt-snac
@@ -24,15 +24,17 @@ print_version() {
 ## CLI PARSING
 usage() {
 	cat <<EOF
-$(basename ${BASH_SOURCE}) [--help] [--version] <config>
+$(basename ${BASH_SOURCE}) [--help] [--version] [--yes] <config>
 
 NI LinuxRT Secured, Network-Attached Configuration utility.
 
 # Options
 -h, --help
-    Print this usage information and exit.
+	Print this usage information and exit.
 -V, --version
 	Print this script's version information and exit.
+-y, --yes
+	Skip user prompts (answer 'yes' to all prompts).
 
 # Commands
 config, configure  Affect the SNAC configuration on this machine.
@@ -48,6 +50,8 @@ EOF
 
 
 positionals=()
+yes=false
+
 while [ $# -ge 1 ]; do case "$1" in
 	-h|--help)
 		usage
@@ -56,6 +60,10 @@ while [ $# -ge 1 ]; do case "$1" in
 	-V|--version)
 		print_version
 		exit 0
+		;;
+	-y|--yes)
+		yes=true
+		shift
 		;;
 	-*|--*)
 		log ERROR "Invalid or unknown option \"$1\"."
@@ -73,16 +81,46 @@ if [ ${#positionals[@]} -lt 1 ]; then\
 	usage
 	exit 2
 fi
-
-# Execute the command
 command=${positionals[0]}
+
+
+# Configure the system for SNAC
+# returns: The return code from configure-nilrt-snac; or 0, when the user does not give final consent.
+cmd_configure() {
+	echo WARNING '!! THIS TOOL IS IN-DEVELOPMENT AND APPROPRIATE ONLY FOR DEVELOPER TESTING !!'
+	echo WARNING '!! Running this tool will irreversibly alter the state of your system.    !!'
+
+	# prompt for consent
+	local consent=false
+	if $yes; then
+		consent=y
+	else
+		read -p "Do you want to continue with SNAC configuration? [y/N] " consent
+	fi
+
+	case "$consent" in
+		[yY]*)
+			bash "${SCRIPT_ROOT}/../lib/nilrt-snac/configure-nilrt-snac"
+
+			echo ""  # Blank line
+			echo "!! A reboot is now required to affect your system configuration. !!"
+			echo "!! Login with user 'root' and no password.                       !!"
+
+			return $?
+			;;
+		*)
+			return 0
+			;;
+	esac
+}
+
 case "$command" in
 	config|configure)
-		bash "${SCRIPT_ROOT}/../lib/nilrt-snac/configure-nilrt-snac"
+		cmd_configure
 		exit $?
 		;;
 	*)
 		log ERROR Unrecognized command \"${command}\"
-		exit 2
+		exit $EX_USAGE
 		;;
 esac
